name: demo-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  # image viever: napari, also includes skimage
  - napari
  # related to jupyter notebooks
  - ipykernel
  - jupyterlab
  # data handling and plotting
  - pandas
  - matplotlib
  # some pip dependencies
  - pip
  - pip:
    - aicspylibczi

